import type { MaterialPreset } from "./types";

export const MATERIAL_PRESETS: MaterialPreset[] = [
  {
    id: "kraft",
    label: "Kraft paper",
    roughness: 0.92,
    metalness: 0,
    color: "#c4a574",
    envMapIntensity: 0.35,
    clearcoat: 0,
    clearcoatRoughness: 0.5,
  },
  {
    id: "white_card",
    label: "White folding carton",
    roughness: 0.78,
    metalness: 0,
    color: "#f2f0ea",
    envMapIntensity: 0.55,
    clearcoat: 0.08,
    clearcoatRoughness: 0.4,
  },
  {
    id: "gloss_plastic",
    label: "Gloss plastic (PET)",
    roughness: 0.18,
    metalness: 0.05,
    color: "#ffffff",
    envMapIntensity: 1.15,
    clearcoat: 0.85,
    clearcoatRoughness: 0.12,
  },
  {
    id: "matte_plastic",
    label: "Matte plastic",
    roughness: 0.55,
    metalness: 0.02,
    color: "#eaeaea",
    envMapIntensity: 0.65,
    clearcoat: 0.15,
    clearcoatRoughness: 0.55,
  },
  {
    id: "corrugated",
    label: "Corrugated (brown)",
    roughness: 0.95,
    metalness: 0,
    color: "#a08060",
    envMapIntensity: 0.25,
    clearcoat: 0,
    clearcoatRoughness: 0.5,
  },
  {
    id: "metallic_foil",
    label: "Gold foil",
    roughness: 0.35,
    metalness: 0.65,
    color: "#d4af37",
    envMapIntensity: 1.4,
    clearcoat: 0.45,
    clearcoatRoughness: 0.2,
  },
  {
    id: "soft_touch_black",
    label: "Soft-touch black",
    roughness: 0.85,
    metalness: 0.02,
    color: "#1c1d21",
    envMapIntensity: 0.4,
    clearcoat: 0.06,
    clearcoatRoughness: 0.7,
  },
  {
    id: "gloss_black",
    label: "Gloss black (PET)",
    roughness: 0.14,
    metalness: 0.05,
    color: "#111114",
    envMapIntensity: 1.2,
    clearcoat: 0.9,
    clearcoatRoughness: 0.1,
  },
  {
    id: "recycled_kraft_dark",
    label: "Recycled kraft (dark)",
    roughness: 0.95,
    metalness: 0,
    color: "#8a6b48",
    envMapIntensity: 0.25,
    clearcoat: 0,
    clearcoatRoughness: 0.5,
  },
  {
    id: "pearl_white",
    label: "Pearlescent white",
    roughness: 0.4,
    metalness: 0.2,
    color: "#f4f1ea",
    envMapIntensity: 1.0,
    clearcoat: 0.6,
    clearcoatRoughness: 0.25,
  },
  {
    id: "silver_foil",
    label: "Silver foil",
    roughness: 0.28,
    metalness: 0.8,
    color: "#cbcdd2",
    envMapIntensity: 1.5,
    clearcoat: 0.4,
    clearcoatRoughness: 0.15,
  },
  {
    id: "rose_gold_foil",
    label: "Rose gold foil",
    roughness: 0.3,
    metalness: 0.75,
    color: "#e0a899",
    envMapIntensity: 1.45,
    clearcoat: 0.4,
    clearcoatRoughness: 0.18,
  },
  {
    id: "copper_foil",
    label: "Copper foil",
    roughness: 0.34,
    metalness: 0.78,
    color: "#b87333",
    envMapIntensity: 1.45,
    clearcoat: 0.4,
    clearcoatRoughness: 0.18,
  },
  {
    id: "frosted_plastic",
    label: "Frosted plastic",
    roughness: 0.6,
    metalness: 0,
    color: "#dfe6ea",
    envMapIntensity: 0.8,
    clearcoat: 0.5,
    clearcoatRoughness: 0.5,
  },
];

export function getPreset(id: string): MaterialPreset {
  return MATERIAL_PRESETS.find((p) => p.id === id) ?? MATERIAL_PRESETS[0];
}
